### ISSUE TITLE
无法正常添加集成，提示Unknown error occurred

### ISSUE THREAD

**Issue by Mdxin** [fineemb/Colorfulclouds-weather#2]
配置->集成->添加继承，单击提交按钮后显示`Unknown error occurred`，无法正常添加。控制台输出如下：
```
2020-10-10 01:49:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "d:\services\homeassistant386\lib\site-packages\aiohttp\web_protocol.py", line 418, in start
    resp = await task
  File "d:\services\homeassistant386\lib\site-packages\aiohttp\web_app.py", line 458, in _handle
    resp = await handler(request)
  File "d:\services\homeassistant386\lib\site-packages\aiohttp\web_middlewares.py", line 119, in impl
    return await handler(request)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\components\http\request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\components\http\ban.py", line 72, in ban_middleware
    return await handler(request)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\components\http\auth.py", line 127, in auth_middleware
    return await handler(request)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\components\http\view.py", line 129, in handle
    result = await result
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\components\config\config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\components\http\data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\helpers\data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\data_entry_flow.py", line 204, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "D:\Services\HomeAssistant386\config\custom_components\colorfulclouds\config_flow.py", line 44, in async_step_user
    json_text = requests.get(str.format("https://api.caiyunapp.com/{}/{}/{},{}/daily.json", user_input["api_version"], user_input["api_key"], user_input["longitude"], user_input["latitude"])).content
  File "d:\services\homeassistant386\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "d:\services\homeassistant386\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "d:\services\homeassistant386\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\services\homeassistant386\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "d:\services\homeassistant386\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "d:\services\homeassistant386\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "d:\services\homeassistant386\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "d:\services\homeassistant386\lib\site-packages\urllib3\connection.py", line 199, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\util\async_.py", line 120, in protected_loop_func
    check_loop()
  File "d:\services\homeassistant386\lib\site-packages\homeassistant\util\async_.py", line 91, in check_loop
    raise RuntimeError(
RuntimeError: Detected I/O inside the event loop. This is causing stability issues. Please report issue
```

**Comment by libingtong** [comment]
遇见同样的问题

**Comment by Mdxin** [comment]
> 遇见同样的问题

是在 Windows 上安装的吗？

**Comment by libingtong** [comment]
后来解决了，只是因为需要科学上网环境。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月11日(周五) 中午11:50
收件人: ***@***.***&gt;;
抄送: "Dylan ***@***.******@***.***&gt;;
主题: Re: [fineemb/Colorfulclouds-weather] 无法正常添加集成，提示Unknown error occurred (#2)




  
遇见同样的问题
  
是在 Windows 上安装的吗？
