### ISSUE TITLE
home assistant core更新2023.3.0后，适配失败

### ISSUE THREAD

**Issue by cnbb002** [fineemb/Colorfulclouds-weather#39]
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/colorfulclouds/__init__.py:129
Integration: colorfulclouds (documentation, issues)
First occurred: 10:38:40 (2 occurrences)
Last logged: 11:06:27

Error setting up entry 彩云天气 for colorfulclouds
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/colorfulclouds/__init__.py", line 69, in async_setup_entry
    coordinator = ColorfulcloudsDataUpdateCoordinator(
  File "/config/custom_components/colorfulclouds/__init__.py", line 129, in __init__
    self.is_metric = hass.config.units.is_metric
AttributeError: 'UnitSystem' object has no attribute 'is_metric'

**Comment by SymlonCheung** [comment]
亲测，只要删除原colorfulclouds文件夹所有文件，手动下载master里的colorfulclouds，按原来的文件结构并修改manifest.json里的version为1.2.8，重启就能用了

**Comment by fineemb** [comment]
更新到v2.0.0
