### ISSUE TITLE
KeyError: 'nearest'

### ISSUE THREAD

**Issue by yandong31** [fineemb/Colorfulclouds-weather#7]
Logger: homeassistant
Source: custom_components/colorfulclouds/sensor.py:181
First occurred: 下午7:32:20 (1 occurrences)
Last logged: 下午7:32:20

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/colorfulclouds/sensor.py", line 181, in device_state_attributes
    self._attrs["nearest_intensity"] = self.coordinator.data["result"]["realtime"]["precipitation"]["nearest"]["intensity"]
KeyError: 'nearest'

**Comment by mingjing99** [comment]
I am having the same issue, is there a fix for this? Thanks!

**Comment by water3033** [comment]
I am also having the same issue, is there a fix for this? Thanks!

**Comment by OliverYN** [comment]
Same problem.
